### ISSUE TITLE
Melodic Release Request

### ISSUE THREAD

**Issue by moriarty** [ros-perception/graft#29]
@chadrockey or @mikeferguson could we merge #25 & #26 and then release this into Melodic?

I forgot about this dependency and had it installed in my melodic workspace and would like to release the fetch packages https://github.com/fetchrobotics/fetch_ros/issues/63  into melodic and this is used.

https://github.com/fetchrobotics/fetch_robots/blob/melodic-devel/fetch_bringup/launch/fetch.launch#L20-L22

**Comment by mikeferguson** [comment]
You want to take over maintenance? I  I've been recommending people move over to robot_localization for quite some time now (it's way better documented), and so I don't have any interest in continuing to maintain it (we didn't add a Fetch maintainer because it was assumed Fetch would be migrating to robot_localization or their internal thing).

**Comment by chadrockey** [comment]
Done for Fetch.

**Comment by moriarty** [comment]
@mikeferguson & @chadrockey thanks.

I'll try to switch to `robot_localization` for the open source code... otherwise I could take over maintenance.

We've moved over to our internal thing for our commercial robots, which is why this was a last minute forgotten dependency which I had installed on to the Fetch back when I was testing the opensource melodic nav stack on the robot.

**Comment by knorth55** [comment]
What is the status of issue?
Is fetch planning to use robot_localization?

**Comment by knorth55** [comment]
I made a PR to swtich from graft to robot_localization https://github.com/fetchrobotics/fetch_robots/pull/56
